Extension { #name : #SmaCCParseNode }

{ #category : #'*Famix-CPP' }
SmaCCParseNode >> additionalCyclomaticComplexityEdges [
	^ 0
]

{ #category : #'*Famix-CPP' }
SmaCCParseNode >> isCPPClass [
	^ false
]

{ #category : #'*Famix-CPP' }
SmaCCParseNode >> isEnum [
	^ false
]

{ #category : #'*Famix-CPP' }
SmaCCParseNode >> isStructure [
	^ false
]

{ #category : #'*Famix-CPP' }
SmaCCParseNode >> isUnion [
	^ false
]
